#!/usr/bin/env python

import os, sys, parsers

if len(sys.argv) != 4:
        print 'Usage: analyse_topics <corpus> <docToTop> <topicID>'
        sys.exit(0)

corpusFile = sys.argv[1]
docToTopFile = sys.argv[2]
topicID = int(sys.argv[3])

docData = parsers.parse_docToTop(docToTopFile)
corpus = parsers.parse_corpus(corpusFile)

total_non_zero_cdk = reduce(lambda x, y : x + y, map(lambda x : len(x), docData.values()), 0)

for key in docData.keys():
        if topicID in docData[key]:
                print docData[key][topicID], ' '.join(corpus[key])

print 'Sparsity = %f' % (float(total_non_zero_cdk) / len(docData))
