set(0,'DefaultAxesFontName', 'Times New Roman')
set(0,'DefaultAxesFontSize', 30)
set(0,'DefaultTextFontname', 'Times New Roman')
set(0,'DefaultTextFontSize', 30)

errorbar(x, truncated(:, 3), truncated(:, 5), 'b^-', 'MarkerSize', 8, 'LineWidth', 2)
hold on; errorbar(x, pg(:, 3), pg(:, 5), 'ro-', 'MarkerSize', 8, 'LineWidth', 2)
hold on; errorbar(x, gaussian(:, 3), gaussian(:, 5), 'k-', 'MarkerSize', 8, 'LineWidth', 2)
xlim([0.8 1300])
set(gca,'xtick',x)
set(gca, 'xscale', 'log')
legend('truncated', 'pg1', 'gaussian')
set(gca, 'xticklabel', {'1'; '2'; '4'; '8'; '16'; '32'; '64'; '128'; '256'; '512'; 'n'})
ylabel('perplexity')
xlabel('m')
