#!/bin/bash

# This will submit a command to lsf, and block until
# the job is complete.

if [ "$#" == "0" ]
then
	command=`cat <&0`
else
	command=$@
fi

# Generate a job id
#id=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16};echo;`
id=`uuidgen -r`

echo "$command" > $id.COMMAND
echo "
touch $id.DONE" >> $id.COMMAND

echo "sh $id.COMMAND > $id.OUTPUT" > $id.METACOMMAND

# Submit
cat $id.METACOMMAND | bsub >/dev/null 2>&1

# Wait
while [ ! -f $id.DONE ]
do
	sleep 20

	if [ -f $id.DONE ]
	then
		break
	fi

	if [ `bjobs -w | grep $id | wc -l` == '0' ]
	then
		if [ ! -f $id.DONE ]
		then
			echo "$id Failed" 1>&2
			break
		fi
	fi
done

cat $id.OUTPUT

rm ${id}*
